[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "noise>=1.2.2",
    "numpy>=2.2.4",
    "pillow>=11.1.0",
    "scipy>=1.15.2",
]
