#pragma once
#define RENDER_DISTANCE 5
#define MAX_CHUNK_TO_RENDER RENDER_DISTANCE*2 * RENDER_DISTANCE*2

#define CHUNK_SIZE_X 4
#define CHUNK_SIZE_Y 4
#define CHUNK_SIZE_Z 4

#define BLOCK(x,y,z) (x + (z*CHUNK_SIZE_X) + (y*CHUNK_SIZE_X*CHUNK_SIZE_Z))
